import React from "react";

function Head(){
    
    return(
        <>
            <title>NextJS 13 Education</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </>
    )
}

export default Head;